### ISSUE TITLE
Problem while in docker environment

### ISSUE THREAD

**Issue by JunyuanDeng** [UMich-CURLY/unified_cvo#3]
Thank you again for providing the environment!

But I met the problem when I use "make -j":
[ 97%] Building CXX object CMakeFiles/cvo_align_gpu_rgbd_tartan.dir/src/experiments/main_cvo_gpu_align_tartan.cpp.o
/usr/bin/c++  -DCUDA_BLOCK_SIZE=512 -DCVO_POINT_NEIGHBORS=256 -DDISABLE_LIBUSB_1_0 -DDISABLE_PCAP -DDISABLE_PNG -DENABLE_SSE -DFEATURE_DIMENSIONS=5 -DNUM_CLASSES=19 -DOPENMP -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -Dqh_QHpointer -DvtkFiltersFlowPaths_AUTOINIT="1(vtkFiltersParallelFlowPaths)" -DvtkIOExodus_AUTOINIT="1(vtkIOParallelExodus)" -DvtkIOGeometry_AUTOINIT="1(vtkIOMPIParallel)" -DvtkIOImage_AUTOINIT="1(vtkIOMPIImage)" -DvtkIOParallel_AUTOINIT="1(vtkIOMPIParallel)" -DvtkIOSQL_AUTOINIT="2(vtkIOMySQL,vtkIOPostgreSQL)" -DvtkRenderingContext2D_AUTOINIT="1(vtkRenderingContextOpenGL)" -DvtkRenderingCore_AUTOINIT="3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL)" -DvtkRenderingFreeType_AUTOINIT="2(vtkRenderingFreeTypeFontConfig,vtkRenderingMatplotlib)" -DvtkRenderingLIC_AUTOINIT="1(vtkRenderingParallelLIC)" -DvtkRenderingVolume_AUTOINIT="1(vtkRenderingVolumeOpenGL)" -isystem /usr/include/vtk-6.3 -isystem /usr/include/freetype2 -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /usr/include/python2.7 -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include/hdf5/openmpi -isystem /usr/include/libxml2 -isystem /usr/include/jsoncpp -isystem /usr/include/tcl -I/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo -isystem /usr/local/include/eigen3 -isystem /usr/local/include/pcl-1.9 -isystem /usr/include/ni -isystem /usr/include/openni2 -isystem /usr/include/opencv -I/usr/include/suitesparse -I/usr/local/lib/cmake/Sophus/../../../include -I/home/juneyoung/Programmes/un/unified_cvo/thirdparty/libelas -I/home/juneyoung/Programmes/un/unified_cvo/thirdparty/cugicp -I/home/juneyoung/Programmes/un/unified_cvo/thirdparty/cnpy -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  -fopenmp   -O3 -DNDEBUG -fPIE   -march=native -msse4.2 -mfpmath=sse -std=c++1z -o CMakeFiles/cvo_align_gpu_rgbd_tartan.dir/src/experiments/main_cvo_gpu_align_tartan.cpp.o -c /home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_tartan.cpp
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp: In function 'int main(int, char**)':
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:65:102: error: class template argument deduction failed:
   std::shared_ptr<cvo::ImageRGBD<uint16_t>> source_raw(new cvo::ImageRGBD(source_rgb, source_dep_data));
                                                                                                      ^
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:65:102: error: no matching function for call to 'ImageRGBD()'
In file included from /home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:17:0:
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:18:5: note: candidate: template<class DepthType> ImageRGBD(const cv::Mat&, const std::vector<_Tp>&, int, const std::vector<float>&)-> cvo::ImageRGBD<DepthType>
     ImageRGBD(const cv::Mat & image,
     ^~~~~~~~~
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:18:5: note:   template argument deduction/substitution failed:
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:65:102: note:   candidate expects 4 arguments, 0 provided
   std::shared_ptr<cvo::ImageRGBD<uint16_t>> source_raw(new cvo::ImageRGBD(source_rgb, source_dep_data));
                                                                                                      ^
In file included from /home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:17:0:
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:14:5: note: candidate: template<class DepthType> ImageRGBD(const cv::Mat&, const std::vector<_Tp>&)-> cvo::ImageRGBD<DepthType>
     ImageRGBD(const cv::Mat & image,
     ^~~~~~~~~
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:14:5: note:   template argument deduction/substitution failed:
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:65:102: note:   candidate expects 2 arguments, 0 provided
   std::shared_ptr<cvo::ImageRGBD<uint16_t>> source_raw(new cvo::ImageRGBD(source_rgb, source_dep_data));
                                                                                                      ^
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:93:97: error: class template argument deduction failed:
     std::shared_ptr<cvo::ImageRGBD<uint16_t>> target_raw(new cvo::ImageRGBD(rgb, target_dep_data));
                                                                                                 ^
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:93:97: error: no matching function for call to 'ImageRGBD()'
In file included from /home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:17:0:
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:18:5: note: candidate: template<class DepthType> ImageRGBD(const cv::Mat&, const std::vector<_Tp>&, int, const std::vector<float>&)-> cvo::ImageRGBD<DepthType>
     ImageRGBD(const cv::Mat & image,
     ^~~~~~~~~
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:18:5: note:   template argument deduction/substitution failed:
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:93:97: note:   candidate expects 4 arguments, 0 provided
     std::shared_ptr<cvo::ImageRGBD<uint16_t>> target_raw(new cvo::ImageRGBD(rgb, target_dep_data));
                                                                                                 ^
In file included from /home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:17:0:
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:14:5: note: candidate: template<class DepthType> ImageRGBD(const cv::Mat&, const std::vector<_Tp>&)-> cvo::ImageRGBD<DepthType>
     ImageRGBD(const cv::Mat & image,
     ^~~~~~~~~
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:14:5: note:   template argument deduction/substitution failed:
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_rgbd.cpp:93:97: note:   candidate expects 2 arguments, 0 provided
     std::shared_ptr<cvo::ImageRGBD<uint16_t>> target_raw(new cvo::ImageRGBD(rgb, target_dep_data));
                                                                                                 ^
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_tartan.cpp: In function 'int main(int, char**)':
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_tartan.cpp:89:82: error: class template argument deduction failed:
 td::shared_ptr<cvo::ImageRGBD<float>> target_raw(new cvo::ImageRGBD(rgb, dep));
                                                                             ^
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_tartan.cpp:89:82: error: no matching function for call to 'ImageRGBD()'
In file included from /home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_tartan.cpp:17:0:
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:18:5: note: candidate: template<class DepthType> ImageRGBD(const cv::Mat&, const std::vector<_Tp>&, int, const std::vector<float>&)-> cvo::ImageRGBD<DepthType>
     ImageRGBD(const cv::Mat & image,
     ^~~~~~~~~
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:18:5: note:   template argument deduction/substitution failed:
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_tartan.cpp:89:82: note:   candidate expects 4 arguments, 0 provided
 td::shared_ptr<cvo::ImageRGBD<float>> target_raw(new cvo::ImageRGBD(rgb, dep));
                                                                             ^
In file included from /home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_tartan.cpp:17:0:
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:14:5: note: candidate: template<class DepthType> ImageRGBD(const cv::Mat&, const std::vector<_Tp>&)-> cvo::ImageRGBD<DepthType>
     ImageRGBD(const cv::Mat & image,
     ^~~~~~~~~
/home/juneyoung/Programmes/un/unified_cvo/include/UnifiedCvo/utils/ImageRGBD.hpp:14:5: note:   template argument deduction/substitution failed:
/home/juneyoung/Programmes/un/unified_cvo/src/experiments/main_cvo_gpu_align_tartan.cpp:89:82: note:   candidate expects 2 arguments, 0 provided
 td::shared_ptr<cvo::ImageRGBD<float>> target_raw(new cvo::ImageRGBD(rgb, dep));
                                                                             ^
CMakeFiles/cvo_align_gpu_rgbd_tartan.dir/build.make:65: recipe for target 'CMakeFiles/cvo_align_gpu_rgbd_tartan.dir/src/experiments/main_cvo_gpu_align_tartan.cpp.o' failed
make[2]: *** [CMakeFiles/cvo_align_gpu_rgbd_tartan.dir/src/experiments/main_cvo_gpu_align_tartan.cpp.o] Error 1
make[2]: Leaving directory '/home/juneyoung/Programmes/un/unified_cvo/build'
CMakeFiles/Makefile2:1110: recipe for target 'CMakeFiles/cvo_align_gpu_rgbd_tartan.dir/all' failed
make[1]: *** [CMakeFiles/cvo_align_gpu_rgbd_tartan.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/cvo_align_gpu_rgbd.dir/build.make:65: recipe for target 'CMakeFiles/cvo_align_gpu_rgbd.dir/src/experiments/main_cvo_gpu_align_rgbd.cpp.o' failed
make[2]: *** [CMakeFiles/cvo_align_gpu_rgbd.dir/src/experiments/main_cvo_gpu_align_rgbd.cpp.o] Error 1
make[2]: Leaving directory '/home/juneyoung/Programmes/un/unified_cvo/build'
CMakeFiles/Makefile2:718: recipe for target 'CMakeFiles/cvo_align_gpu_rgbd.dir/all' failed
make[1]: *** [CMakeFiles/cvo_align_gpu_rgbd.dir/all] Error 2
make[1]: Leaving directory '/home/juneyoung/Programmes/un/unified_cvo/build'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error  2

could you please help me to solve this promblem?

**Comment by JunyuanDeng** [comment]
Also, when I execute the files that are compiled successfully, for example, in this command line 
```./build/bin/cvo_irls_tum /home/rayzhang/media/Samsung_T5/tum/freiburg1_360 cvo_params/cvo_intensity_params_irls_tum.yaml graph_defs/tum_fr1_360/70_graph.txt /home/rayzhang/media/Samsung_T5/tum/freiburg1_360/CVO.txt  5```  

what is`CVO.txt` file? And also, I cannot find `'cvo_geometric_img_jan11_00.txt'` or  ` cvo_img_semantic_00.txt` in this resposirory.

**Comment by zeroAska** [comment]
Which gcc version are you using with `gcc --version`? Is it `gcc-9`? You could also try to add the template argument, for example:


```
std::shared_ptr<cvo::ImageRGBD<uint16_t>> target_raw(new cvo::ImageRGBD<uint16_t>(rgb, target_dep_data));
```
instead of the original 
```
std::shared_ptr<cvo::ImageRGBD<uint16_t>> target_raw(new cvo::ImageRGBD(rgb, target_dep_data));
```

Regarding your second question: This is the running script for the multi-frame registration, which is still under-development. I would provide the doc for using this script in the future

**Comment by zeroAska** [comment]
I have added a simplified example of aligning two point clouds. 

[Example](https://github.com/UMich-CURLY/unified_cvo/blob/multiframe/README.md#example-of-aligning-two-point-clouds)

**Comment by JunyuanDeng** [comment]
Thanks for your reply! I have compiled successfully and I run the Example you provided.

But I got another problems when I run the  ```Frame-to-Frame Registration Demo on Kitti```
1. In file ```kitti_geometric_stereo.bash```, ```./build/bin/cvo_align_gpu_geometric_img``` cannot be found.
2. In file ```kitti_intensity_stereo.bash```, ```./build/bin/cvo_align_gpu_intensity_img``` cannot be found.
3. How does the ```/home/rayzhang/data/kitti/00/cvo_calib.txt``` look like?
4. When I tried to run ```cvo_semantic_img_oct26_gpu0.bash```, where can I find the file ```dataset/KittiData/00/image_semantic/xxxxxx.bin```? Should I download [here](http://semantic-kitti.org/dataset.html)?


I try to solve the first two problems using ```cvo_align_gpu_img``` like this, but it seems wrong:
```
root@juneyoung:/home/juneyoung/Programmes/unified_cvo# ./build/bin/cvo_align_gpu_img /media/juneyoung/Samsung_T51/dataset/KittiData/color/00 cvo_params/cvo_intensity_params_img_gpu0.yaml  cvo_intensity_img_jan11_$i.txt 0 20000
Kitti contains 4541 files
 calibration file /media/juneyoung/Samsung_T51/dataset/KittiData/color/00/cvo_calib.txt not found!
open cvo_params/cvo_intensity_params_img_gpu0.yaml
read: ell_init is 0.15, MAX_ITER is 100000, c is 7, d is 7, indicator window size is 30
Some Cvo Params are: ell_init: 0.150000, eps_2: 0.000012
write ell! ell init is 1.5
read source raw...
build source CvoPointCloud...
write to opcd




=============================================
Aligning 0 and 1 with GPU 
Start align... num_fixed is 11792, num_moving is 11402
[align] convert points to gpu
construct new cvo state..., init ell is 1.5
Start iteration, init transform is 
 1 -0  0 -0
-0  1 -0  0
 0 -0  1 -0
-0  0 -0  1
Max iter is 100000
iter=0: nonzeros in A is 1671199
break: norm, omega: 0, v: 0
cvo # of iterations is 0
final max num of neighbors is 256
t_all is 0.151675
non adaptive cvo ends. final ell is 1.5, final iteration is 0MAX_ITER is 100000
Transform is  1 -0  0  0
-0  1 -0 -0
 0 -0  1  0
 0  0  0  1

accum tf: 
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1


===========next frame=============





=============================================
Aligning 1 and 2 with GPU 
Start align... num_fixed is 11402, num_moving is 11823
[align] convert points to gpu
construct new cvo state..., init ell is 0.15
Start iteration, init transform is 
 1 -0  0 -0
-0  1 -0  0
 0 -0  1 -0
-0  0 -0  1
Max iter is 100000
iter=0: nonzeros in A is 1605009
break: norm, omega: 0, v: 0
cvo # of iterations is 0
final max num of neighbors is 256
t_all is 0.116507
non adaptive cvo ends. final ell is 0.15, final iteration is 0MAX_ITER is 100000
Transform is  1 -0  0  0
-0  1 -0 -0
 0 -0  1  0
 0  0  0  1

accum tf: 
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1


===========next frame=============





=============================================
Aligning 2 and 3 with GPU 

```

**Comment by zeroAska** [comment]
Thanks for the following up questions! 

> 1. In file kitti_geometric_stereo.bash, ./build/bin/cvo_align_gpu_geometric_img cannot be found.
> 2. In file kitti_intensity_stereo.bash, ./build/bin/cvo_align_gpu_intensity_img cannot be found.

Good catch. These two files have been merged to a single file:  ./build/bin/cvo_align_gpu_img. Now we use the [param file](https://github.com/UMich-CURLY/unified_cvo/blob/7c946cf7fec8fd27833a76b8ce6b3ff5c13d228e/cvo_params/cvo_intensity_params_img_gpu0.yaml#L33)  to control whether it is using geometric only or intensity. 
For example,
```
is_using_geometry: 1            # if geoemtric kernel is computed k(x,z)                                                                                                                       
is_using_intensity: 0           # if color kernel is computed <l_x, l_z>. Enable it if using color info                                                                                                              
```
means using geometric info only without intensity.

> How does the /home/rayzhang/data/kitti/00/cvo_calib.txt look like?

Here [doc](https://github.com/UMich-CURLY/unified_cvo#example-calibration-file-cvo_calibtxt)

> When I tried to run cvo_semantic_img_oct26_gpu0.bash, where can I find the file dataset/KittiData/00/image_semantic/xxxxxx.bin? Should I download [here](http://semantic-kitti.org/dataset.html)?

The image semantics are actually generated by the pretrained networks from [nvidia-segmentation](https://github.com/NVIDIA/semantic-segmentation) where the bin files are the semantic distribution image. For example, for a 640x480 image with 19 classes, the size of the bin files is sizeof(float) * 640 * 480 * 19.


> I try to solve the first two problems using cvo_align_gpu_img like this, but it seems wrong:

It's because the `cvo_calib.txt` file is not provided.  It has to be put in each sequence folder.

**Comment by JunyuanDeng** [comment]
Thanks a lot! Now I can use the file ./build/bin/cvo_align_gpu_img and the result is correct! 

But how can show the UI window (e.g. Pangolin in ORB-SLAM2) simultaneously when I run the program, like the three png images in the [result](https://github.com/UMich-CURLY/unified_cvo/tree/multiframe/results).

**Comment by zeroAska** [comment]
Those are pngs are generated by a third package running ros. You would need to implement your own main file and UI functions, and call the `align()`  function yourself. Ways of exporting this lib to a third party package can be seen [here](https://github.com/UMich-CURLY/unified_cvo#how-to-use-the-library)

If you want to see the registration results easily, I suggest you transform all the point clouds based on the result transformation and write them to pcd files.  For example, our [customized point cloud type](https://github.com/UMich-CURLY/unified_cvo/blob/multiframe/include/UnifiedCvo/utils/CvoPointCloud.hpp) has a native  [transform()](https://github.com/UMich-CURLY/unified_cvo/blob/8dda2c7233b61d9ecaec0d8931d2f7cfe4c1c207/include/UnifiedCvo/utils/CvoPointCloud.hpp#L136) function and  [write_to_color_pcd()](https://github.com/UMich-CURLY/unified_cvo/blob/8dda2c7233b61d9ecaec0d8931d2f7cfe4c1c207/include/UnifiedCvo/utils/CvoPointCloud.hpp#L166) function. You can also use [export_to_pcd ()](https://github.com/UMich-CURLY/unified_cvo/blob/8dda2c7233b61d9ecaec0d8931d2f7cfe4c1c207/include/UnifiedCvo/utils/CvoPointCloud.hpp#L165) to convert to a pcl point cloud and visualize it.

Our docker container supports GUI from inside [Note](https://github.com/UMich-CURLY/docker_images/tree/master/cvo_gpu#note)

**Comment by JunyuanDeng** [comment]
Thank you for your kindly reply! It really helps me a lot!
